# Use Rust to build
FROM rustlang/rust:nightly as builder

# Add source code to the build stage.
ADD . /tendril
WORKDIR /tendril

RUN cargo install cargo-fuzz

# BUILD INSTRUCTIONS
WORKDIR /tendril/fuzz
RUN cargo +nightly fuzz build pop_back && \
    cargo +nightly fuzz build pop_front && \
    cargo +nightly fuzz build string_bytes_eq_tendril && \
    cargo +nightly fuzz build subtendril && \
    cargo +nightly fuzz build try_push_char
# Output binaries are placed in /tendril/fuzz/target/x86_64-unknown-linux-gnu/release/

# Package Stage -- we package for a plain Ubuntu machine
FROM --platform=linux/amd64 ubuntu:20.04

# Copy the binary from the build stage to an Ubuntu docker image
COPY --from=builder /tendril/fuzz/target/x86_64-unknown-linux-gnu/release/pop_back /tendril/fuzz/target/x86_64-unknown-linux-gnu/release/pop_front /tendril/fuzz/target/x86_64-unknown-linux-gnu/release/string_bytes_eq_tendril /tendril/fuzz/target/x86_64-unknown-linux-gnu/release/subtendril /tendril/fuzz/target/x86_64-unknown-linux-gnu/release/try_push_char /